### ISSUE TITLE
Dockerfile 만들기.

### ISSUE THREAD

**Issue by teang1995** [teang1995/pytorch-autorec#1]
### What?
Dockerfile을 만들어야 한다.
pytorch-lightning 기반의 Docker Image를 도커허브에서 받아오고,
그걸 Base로 하여 Dockerfile을 만든다.

### Why?
WSL+ubuntu에서 개발 중인데, 언제든 gpu서버로 넘길 수 있게끔!
로컬에서 프로토타입이 완성되면 서버로 옮겨 학습 시킬 예정.

### TODO List
- [x] Pytorch-lightning 이미지 Dockerhub에서 찾아보기
- [x] 적합한 이미지 받고, requirements 뽑기.
- [x] 해당 이미지로부터 Image빌드하는 Dockerfile 작성.

**Comment by teang1995** [comment]
우선 도커파일 만드는 건 마무리.  requirements나 도커파일 수정할 부분이 있다면 본 이슈에서 다시 다루도록 하겠음.
